# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoveWalking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LoveWalking

pod 'AFNetworking'
pod ‘Masonry’
pod 'SDWebImage'
pod 'YYModel'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'AMapSearch’
pod 'AMap3DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod ‘PNChart’

end
